// Generated from components/chat/ModelBrandIcon.tsx.
const brandAssets = {
  "anthropic": {
    "background": "#f1f0e8",
    "foreground": "#141413",
    "slug": "anthropic",
  },
  "chatglm": {
    "background": "linear-gradient(135deg, #3485ff, #504af4)",
    "foreground": "#fff",
    "slug": "chatglm",
  },
  "claude": {"background": "#d97757", "foreground": "#fff", "slug": "claude"},
  "deepseek": {
    "background": "#4d6bfe",
    "foreground": "#fff",
    "slug": "deepseek",
  },
  "doubao": {
    "avatarSlug": "doubao-color",
    "background": "#fff",
    "foreground": "#111",
    "slug": "doubao",
  },
  "gemini": {
    "avatarSlug": "gemini-color",
    "background": "#fff",
    "foreground": "#111",
    "scale": 0.8,
    "slug": "gemini",
  },
  "gemma": {
    "background": "linear-gradient(135deg, #446eff 14%, #2e96ff 45%, #b1c5ff)",
    "foreground": "#fff",
    "scale": 0.88,
    "slug": "gemma",
  },
  "grok": {"background": "#050505", "foreground": "#fff", "slug": "grok"},
  "groq": {"background": "#f55036", "foreground": "#fff", "slug": "groq"},
  "huggingface": {
    "background": "#ffd21e",
    "foreground": "#111",
    "slug": "huggingface",
  },
  "infinigence": {
    "background": "#7952ea",
    "foreground": "#fff",
    "scale": 0.62,
    "slug": "infinigence",
  },
  "meta": {
    "background": "linear-gradient(135deg, #007ff8, #0668e1, #007ff8)",
    "foreground": "#fff",
    "slug": "meta",
  },
  "nanobanana": {
    "background": "#fcd53f",
    "foreground": "#111",
    "scale": 0.8,
    "slug": "nanobanana",
  },
  "minimax": {
    "background": "linear-gradient(135deg, #e2167e, #fe603c)",
    "foreground": "#fff",
    "slug": "minimax",
  },
  "mistral": {"background": "#fa520f", "foreground": "#fff", "slug": "mistral"},
  "moonshot": {
    "background": "#16191e",
    "foreground": "#fff",
    "slug": "moonshot",
  },
  "xiaomimimo": {
    "background": "#050505",
    "foreground": "#fff",
    "scale": 0.82,
    "slug": "xiaomimimo",
  },
  "openai": {"background": "#050505", "foreground": "#fff", "slug": "openai"},
  "openrouter": {
    "background": "#050505",
    "foreground": "#c8ff00",
    "slug": "openrouter",
  },
  "qwen": {
    "background": "linear-gradient(135deg, #6336e7, #6f69f7)",
    "foreground": "#fff",
    "slug": "qwen",
  },
  "siliconcloud": {
    "background": "#6e29f6",
    "foreground": "#fff",
    "slug": "siliconcloud",
  },
  "together": {"background": "#fff", "foreground": "#111", "slug": "together"},
  "volcengine": {
    "background": "#1664ff",
    "foreground": "#fff",
    "slug": "volcengine",
  },
  "xai": {
    "background": "#050505",
    "foreground": "#fff",
    "scale": 0.66,
    "slug": "xai",
  },
  "bytedance": {
    "background": "#325ab4",
    "foreground": "#fff",
    "scale": 0.6,
    "slug": "bytedance",
  },
  "glmv": {
    "background": "#0039c6",
    "foreground": "#fff",
    "scale": 0.7,
    "slug": "glmv",
  },
  "jimeng": {
    "background": "#050505",
    "foreground": "#fff",
    "scale": 0.6,
    "slug": "jimeng",
  },
  "zai": {
    "background": "#050505",
    "foreground": "#fff",
    "scale": 0.6,
    "slug": "zai",
  },
  "zhipu": {"background": "#3859ff", "foreground": "#fff", "slug": "zhipu"},
};
const providerAssetKeys = {
  "anthropic": "anthropic",
  "bailian": "qwen",
  "deepseek": "deepseek",
  "gemini": "gemini",
  "google": "gemini",
  "groq": "groq",
  "huggingface": "huggingface",
  "infiniai": "infinigence",
  "infinigence": "infinigence",
  "minimax": "minimax",
  "mistral": "mistral",
  "moonshot": "moonshot",
  "moonshotai": "moonshot",
  "mimo": "xiaomimimo",
  "xiaomi": "xiaomimimo",
  "xiaomimimo": "xiaomimimo",
  "openai": "openai",
  "openrouter": "openrouter",
  "qwen": "qwen",
  "siliconcloud": "siliconcloud",
  "siliconflow": "siliconcloud",
  "together": "together",
  "volcengine": "volcengine",
  "xai": "xai",
  "zhipu": "zhipu",
  "zhipuai": "zhipu",
};
const modelAssetRules = [
  {"key": "claude", "pattern": "claude"},
  {
    "key": "nanobanana",
    "pattern": "(?:gemini[^/]*(?:flash|pro)[^/]*image|nanobanana|nano-banana)",
  },
  {"key": "gemini", "pattern": "gemini"},
  {"key": "gemma", "pattern": "gemma"},
  {"key": "deepseek", "pattern": "deepseek"},
  {"key": "qwen", "pattern": "(?:^|[/_.-])(?:qwen|qwq)"},
  {"key": "grok", "pattern": "(?:^|[/_.-])grok(?:\$|[/_.-])"},
  {"key": "meta", "pattern": "(?:llama|meta-llama)"},
  {"key": "glmv", "pattern": "(?:^|\\/)glm-[^/]*v(?:\$|[/_.-])"},
  {"key": "zai", "pattern": "(?:^|[/_.-])glm[-_.]?[45](?:\$|[/_.-])"},
  {"key": "chatglm", "pattern": "(?:chatglm|(?:^|[/_.-])glm-)"},
  {"key": "jimeng", "pattern": "(?:jimeng|seedream|seededit|seedance)"},
  {"key": "doubao", "pattern": "(?:^|\\/)ep-|doubao-"},
  {"key": "bytedance", "pattern": "(?:skylark|(?:^|[/_.-])seed-|bytedance)"},
  {"key": "minimax", "pattern": "(?:minimax|abab)"},
  {"key": "mistral", "pattern": "(?:mistral|mixtral|codestral|pixtral)"},
  {"key": "moonshot", "pattern": "(?:kimi|moonshot)"},
  {
    "key": "xiaomimimo",
    "pattern": "(?:xiaomi[^/]*mimo|(?:^|[/_.-])mimo(?:\$|[/_.-]))",
  },
  {
    "key": "openai",
    "pattern": "(?:gpt|chatgpt|(?:^|[/_.-])o[1345](?:\$|[/_.-])|dall-e|sora)",
  },
];
