export type ModelMetadata = {
  aliases?: string[];
  contextWindowTokens: number;
  description: string;
  displayName: string;
  family: string;
  id: string;
  knowledgeCutoff?: string;
  maxOutputTokens?: number;
  sourceUrl: string;
  verifiedAt: string;
};

const VERIFIED_AT = "2026-07-18";
const DOUBAO_SOURCE_URL = "https://www.volcengine.com/docs/82379/1330310";

// Keep this list deliberately conservative. Unknown/custom models remain unknown instead of
// inheriting an unsafe context limit from a similarly named model.
export const MODEL_METADATA: ModelMetadata[] = [
  {
    aliases: ["gpt-5.4-pro"],
    contextWindowTokens: 1_050_000,
    description: "面向复杂专业工作与高难度推理的 OpenAI 前沿模型。",
    displayName: "GPT-5.4",
    family: "GPT-5",
    id: "gpt-5.4",
    knowledgeCutoff: "2025-08",
    maxOutputTokens: 128_000,
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5.4",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 400_000,
    description: "兼顾成本与能力的 GPT-5.4 轻量型号，适合编码与高频任务。",
    displayName: "GPT-5.4 mini",
    family: "GPT-5",
    id: "gpt-5.4-mini",
    knowledgeCutoff: "2025-08",
    maxOutputTokens: 128_000,
    sourceUrl: "https://developers.openai.com/api/docs/models",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 400_000,
    description: "面向简单、高并发任务的低成本 GPT-5.4 型号。",
    displayName: "GPT-5.4 nano",
    family: "GPT-5",
    id: "gpt-5.4-nano",
    knowledgeCutoff: "2025-08",
    maxOutputTokens: 128_000,
    sourceUrl: "https://developers.openai.com/api/docs/models",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["gpt-5.2-codex"],
    contextWindowTokens: 400_000,
    description: "擅长编码、代理工作流和长上下文推理的旗舰模型。",
    displayName: "GPT-5.2",
    family: "GPT-5",
    id: "gpt-5.2",
    knowledgeCutoff: "2025-08",
    maxOutputTokens: 128_000,
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5.2",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["gpt-5-mini", "gpt-5-nano"],
    contextWindowTokens: 400_000,
    description: "适合跨领域编码、推理和工具调用的通用 GPT-5 模型。",
    displayName: "GPT-5",
    family: "GPT-5",
    id: "gpt-5",
    knowledgeCutoff: "2024-09",
    maxOutputTokens: 128_000,
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["gpt-4.1-mini", "gpt-4.1-nano"],
    contextWindowTokens: 1_047_576,
    description: "具备百万级上下文，适合长文档、代码库和复杂指令处理。",
    displayName: "GPT-4.1",
    family: "GPT-4.1",
    id: "gpt-4.1",
    knowledgeCutoff: "2024-06",
    maxOutputTokens: 32_768,
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-4.1",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 200_000,
    description: "OpenAI 小型推理模型，适合数学、编码和视觉推理。",
    displayName: "o4-mini",
    family: "OpenAI o-series",
    id: "o4-mini",
    maxOutputTokens: 100_000,
    sourceUrl: "https://developers.openai.com/api/docs/models/o4-mini",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 1_114_112,
    description: "Google 面向速度优化的高级多模态推理模型，支持搜索与 grounding。",
    displayName: "Gemini 3.5 Flash",
    family: "Gemini 3.5",
    id: "gemini-3.5-flash",
    knowledgeCutoff: "2025-01",
    maxOutputTokens: 65_536,
    sourceUrl: "https://ai.google.dev/gemini-api/docs/models",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["gemini-3.1-pro-preview", "gemini-pro-latest"],
    contextWindowTokens: 1_114_112,
    description:
      "Gemini 3.1 Pro 在 Gemini 3 Pro 基础上增强复杂推理，并支持更细粒度的思考强度控制。",
    displayName: "Gemini 3.1 Pro",
    family: "Gemini 3.1",
    id: "gemini-3.1-pro",
    knowledgeCutoff: "2025-01",
    maxOutputTokens: 65_536,
    sourceUrl: "https://ai.google.dev/gemini-api/docs/models",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["gemini-3.1-flash-lite-preview", "gemini-flash-lite-latest"],
    contextWindowTokens: 1_114_112,
    description: "Google 面向高吞吐代理任务、翻译和数据处理的高性价比多模态模型。",
    displayName: "Gemini 3.1 Flash-Lite",
    family: "Gemini 3.1",
    id: "gemini-3.1-flash-lite",
    knowledgeCutoff: "2025-01",
    maxOutputTokens: 65_536,
    sourceUrl: "https://ai.google.dev/gemini-api/docs/models",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["gemini-3-flash", "gemini-flash-latest"],
    contextWindowTokens: 1_114_112,
    description: "兼顾前沿推理、生成速度与搜索 grounding 的 Gemini 3 快速型号。",
    displayName: "Gemini 3 Flash",
    family: "Gemini 3",
    id: "gemini-3-flash-preview",
    knowledgeCutoff: "2025-01",
    maxOutputTokens: 65_536,
    sourceUrl: "https://ai.google.dev/gemini-api/docs/models",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 1_048_576,
    description: "Google 高级推理模型，适合复杂代码、数学和长文档分析。",
    displayName: "Gemini 2.5 Pro",
    family: "Gemini 2.5",
    id: "gemini-2.5-pro",
    knowledgeCutoff: "2025-01",
    maxOutputTokens: 65_536,
    sourceUrl: "https://ai.google.dev/gemini-api/docs/models",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["gemini-2.5-flash-lite"],
    contextWindowTokens: 1_048_576,
    description: "兼顾速度、成本和推理能力的 Google 多模态模型。",
    displayName: "Gemini 2.5 Flash",
    family: "Gemini 2.5",
    id: "gemini-2.5-flash",
    knowledgeCutoff: "2025-01",
    maxOutputTokens: 65_536,
    sourceUrl: "https://ai.google.dev/gemini-api/docs/models",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["deepseek-v4-pro"],
    contextWindowTokens: 1_048_576,
    description: "DeepSeek 百万级上下文旗舰系列，支持思考、结构化输出和代理任务。",
    displayName: "DeepSeek V4",
    family: "DeepSeek V4",
    id: "deepseek-v4-flash",
    maxOutputTokens: 393_216,
    sourceUrl: "https://api-docs.deepseek.com/quick_start/pricing",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["deepseek-reasoner"],
    contextWindowTokens: 131_072,
    description: "DeepSeek 通用对话与推理模型，支持思考和工具调用场景。",
    displayName: "DeepSeek Chat",
    family: "DeepSeek",
    id: "deepseek-chat",
    maxOutputTokens: 65_536,
    sourceUrl: "https://api-docs.deepseek.com/quick_start/pricing",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 1_000_000,
    description: "支持超长上下文、中文和多语言任务的通义千问增强模型。",
    displayName: "Qwen Plus",
    family: "Qwen",
    id: "qwen-plus",
    maxOutputTokens: 32_768,
    sourceUrl: "https://help.aliyun.com/zh/model-studio/models",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 131_072,
    description: "通义千问旗舰型号，适合复杂推理、写作和长文本任务。",
    displayName: "Qwen Max",
    family: "Qwen",
    id: "qwen-max",
    maxOutputTokens: 8192,
    sourceUrl: "https://help.aliyun.com/zh/model-studio/models",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 262_144,
    description: "面向深度推理与通用 Agent 的 Kimi 思考模型，擅长通过多步工具调用解决复杂问题。",
    displayName: "Kimi K2 Thinking",
    family: "Kimi K2",
    id: "kimi-k2-thinking",
    maxOutputTokens: 65_536,
    sourceUrl: "https://platform.kimi.com/docs/pricing/chat",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 262_144,
    description: "Kimi 原生多模态推理模型，支持图像、文本、思考与非思考模式以及对话和 Agent 任务。",
    displayName: "Kimi K2.5",
    family: "Kimi K2",
    id: "kimi-k2.5",
    maxOutputTokens: 32_768,
    sourceUrl: "https://platform.kimi.com/docs/pricing/chat",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 262_144,
    description: "Kimi 长任务旗舰模型，强化编码、指令遵循与自我纠错，并支持文本、图像和视频输入。",
    displayName: "Kimi K2.6",
    family: "Kimi K2",
    id: "kimi-k2.6",
    maxOutputTokens: 32_768,
    sourceUrl: "https://platform.kimi.com/docs/pricing/chat",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 8192,
    description: "Moonshot 短上下文型号，适合快速对话和短文本生成。",
    displayName: "Moonshot V1 8K",
    family: "Kimi",
    id: "moonshot-v1-8k",
    maxOutputTokens: 4096,
    sourceUrl: "https://platform.moonshot.cn/docs/guide/start-using-kimi-api",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 32_768,
    description: "Moonshot 中等上下文型号，适合报告和长文档问答。",
    displayName: "Moonshot V1 32K",
    family: "Kimi",
    id: "moonshot-v1-32k",
    maxOutputTokens: 8192,
    sourceUrl: "https://platform.moonshot.cn/docs/guide/start-using-kimi-api",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 131_072,
    description: "Moonshot 长上下文型号，适合多文档分析和研究任务。",
    displayName: "Moonshot V1 128K",
    family: "Kimi",
    id: "moonshot-v1-128k",
    maxOutputTokens: 8192,
    sourceUrl: "https://platform.moonshot.cn/docs/guide/start-using-kimi-api",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 1_000_000,
    description:
      "小米旗舰长上下文模型，强化复杂软件工程、通用 Agent 与千次以上工具调用的长程任务。",
    displayName: "MiMo-V2.5 Pro",
    family: "MiMo",
    id: "mimo-v2.5-pro",
    knowledgeCutoff: "2024-12",
    maxOutputTokens: 131_072,
    sourceUrl: "https://platform.xiaomimimo.com/",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 1_000_000,
    description: "MiniMax 多模态编码与代理模型，提供百万级上下文。",
    displayName: "MiniMax M3",
    family: "MiniMax",
    id: "minimax-m3",
    maxOutputTokens: 524_288,
    sourceUrl: "https://platform.minimaxi.com/docs/guides/models-intro",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["minimax-m2.7-highspeed"],
    contextWindowTokens: 204_800,
    description: "MiniMax 自进化编码与 Agent 模型，面向复杂任务，并提供更高速的同能力版本。",
    displayName: "MiniMax M2.7",
    family: "MiniMax M2",
    id: "minimax-m2.7",
    maxOutputTokens: 131_072,
    sourceUrl: "https://platform.minimaxi.com/docs/guides/models-intro",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["minimax-m2.5-highspeed", "minimax-m2.5-free"],
    contextWindowTokens: 204_800,
    description: "兼顾复杂任务能力与成本的 MiniMax 编码和 Agent 模型，并提供高速推理版本。",
    displayName: "MiniMax M2.5",
    family: "MiniMax M2",
    id: "minimax-m2.5",
    maxOutputTokens: 131_072,
    sourceUrl: "https://platform.minimaxi.com/docs/guides/models-intro",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["minimax-m2.1-highspeed"],
    contextWindowTokens: 204_800,
    description: "强化多语言编程能力的 MiniMax 模型，适合代码生成、工程任务和 Agent 工作流。",
    displayName: "MiniMax M2.1",
    family: "MiniMax M2",
    id: "minimax-m2.1",
    maxOutputTokens: 131_072,
    sourceUrl: "https://platform.minimaxi.com/docs/guides/models-intro",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-2-1-pro", "doubao-seed-2-1-pro-260628"],
    contextWindowTokens: 256_000,
    description:
      "字节跳动新一代 Agent 通用旗舰模型，强化编码、代理规划、长链路执行和原生多模态理解。",
    displayName: "Doubao Seed 2.1 Pro",
    family: "Doubao Seed 2.1",
    id: "doubao-seed-2.1-pro",
    maxOutputTokens: 128_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-2-1-turbo", "doubao-seed-2-1-turbo-260628"],
    contextWindowTokens: 256_000,
    description: "面向高并发生产场景的豆包模型，在推理、Agent 能力、速度和成本之间取得平衡。",
    displayName: "Doubao Seed 2.1 Turbo",
    family: "Doubao Seed 2.1",
    id: "doubao-seed-2.1-turbo",
    maxOutputTokens: 128_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-2-0-pro", "doubao-seed-2-0-pro-260215"],
    contextWindowTokens: 256_000,
    description: "字节跳动旗舰 Agent 通用模型，重点提升复杂任务规划、推理和执行能力。",
    displayName: "Doubao Seed 2.0 Pro",
    family: "Doubao Seed 2.0",
    id: "doubao-seed-2.0-pro",
    maxOutputTokens: 128_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-2-0-lite", "doubao-seed-2-0-lite-260428"],
    contextWindowTokens: 256_000,
    description: "兼顾成本和通用任务能力的豆包多模态深度推理模型，适合常规生产工作负载。",
    displayName: "Doubao Seed 2.0 Lite",
    family: "Doubao Seed 2.0",
    id: "doubao-seed-2.0-lite",
    maxOutputTokens: 128_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-2-0-mini", "doubao-seed-2-0-mini-260428"],
    contextWindowTokens: 256_000,
    description: "面向轻量任务和高并发场景的豆包快速模型，保留多模态、推理和工具调用能力。",
    displayName: "Doubao Seed 2.0 Mini",
    family: "Doubao Seed 2.0",
    id: "doubao-seed-2.0-mini",
    maxOutputTokens: 128_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-2-0-code", "doubao-seed-2-0-code-preview-260215"],
    contextWindowTokens: 256_000,
    description: "针对 Agentic Coding 深度优化的豆包模型，支持多模态输入、代码任务和工具工作流。",
    displayName: "Doubao Seed 2.0 Code",
    family: "Doubao Seed 2.0",
    id: "doubao-seed-2.0-code",
    maxOutputTokens: 128_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-1-8", "doubao-seed-1-8-251228"],
    contextWindowTokens: 256_000,
    description: "强化多模态理解与 Agent 能力的豆包模型，支持文本、图像、视频和上下文缓存。",
    displayName: "Doubao Seed 1.8",
    family: "Doubao Seed 1.8",
    id: "doubao-seed-1.8",
    maxOutputTokens: 64_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-code-preview", "doubao-seed-code-preview-251028"],
    contextWindowTokens: 256_000,
    description: "豆包代码和 Agent 工作流模型，支持文本、图像、视频输入及 Anthropic API 兼容调用。",
    displayName: "Doubao Seed Code",
    family: "Doubao Seed",
    id: "doubao-seed-code",
    maxOutputTokens: 32_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-1-6", "doubao-seed-1-6-251015"],
    contextWindowTokens: 256_000,
    description: "豆包多模态深度推理模型，提供自动、思考和非思考模式，适合通用对话与 Agent 任务。",
    displayName: "Doubao Seed 1.6",
    family: "Doubao Seed 1.6",
    id: "doubao-seed-1.6",
    maxOutputTokens: 32_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-1-6-flash", "doubao-seed-1-6-flash-250828"],
    contextWindowTokens: 256_000,
    description: "低延迟的豆包多模态深度推理模型，面向快速文本、视觉理解和高吞吐任务。",
    displayName: "Doubao Seed 1.6 Flash",
    family: "Doubao Seed 1.6",
    id: "doubao-seed-1.6-flash",
    maxOutputTokens: 32_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-seed-1-6-vision", "doubao-seed-1-6-vision-250815"],
    contextWindowTokens: 256_000,
    description: "针对图像、文档、教育和检索问答优化的豆包视觉深度推理模型。",
    displayName: "Doubao Seed 1.6 Vision",
    family: "Doubao Seed 1.6",
    id: "doubao-seed-1.6-vision",
    maxOutputTokens: 32_000,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-1-5-pro-32k", "doubao-1-5-pro-32k-250115"],
    contextWindowTokens: 128_000,
    description: "豆包 1.5 旗舰通用模型，全面提升知识、编码和推理能力。",
    displayName: "Doubao 1.5 Pro 32K",
    family: "Doubao 1.5",
    id: "doubao-1.5-pro-32k",
    maxOutputTokens: 16_384,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-1-5-pro-256k", "doubao-1-5-pro-256k-250115"],
    contextWindowTokens: 256_000,
    description: "豆包 1.5 Pro 的长上下文版本，适合大文档、复杂对话和长输入任务。",
    displayName: "Doubao 1.5 Pro 256K",
    family: "Doubao 1.5",
    id: "doubao-1.5-pro-256k",
    maxOutputTokens: 12_288,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-1-5-lite-32k", "doubao-1-5-lite-32k-250115"],
    contextWindowTokens: 32_768,
    description: "面向低延迟和高性价比场景的豆包 1.5 轻量通用模型。",
    displayName: "Doubao 1.5 Lite 32K",
    family: "Doubao 1.5",
    id: "doubao-1.5-lite-32k",
    maxOutputTokens: 12_288,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["doubao-1-5-vision-pro-32k", "doubao-1-5-vision-pro-32k-250115"],
    contextWindowTokens: 32_768,
    description: "豆包 1.5 多模态旗舰模型，强化视觉推理、文档识别、细节理解和指令遵循。",
    displayName: "Doubao 1.5 Vision Pro 32K",
    family: "Doubao 1.5",
    id: "doubao-1.5-vision-pro-32k",
    maxOutputTokens: 12_288,
    sourceUrl: DOUBAO_SOURCE_URL,
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 1_000_000,
    description:
      "智谱面向长程任务的旗舰模型，提供百万级上下文，并强化长期规划、复杂编码和 Agent 执行。",
    displayName: "GLM-5.2",
    family: "GLM-5",
    id: "glm-5.2",
    maxOutputTokens: 131_072,
    sourceUrl: "https://docs.bigmodel.cn/cn/guide/start/model-overview",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 200_000,
    description: "智谱长程任务旗舰模型，强化复杂编码、自主规划、持续执行和迭代能力。",
    displayName: "GLM-5.1",
    family: "GLM-5",
    id: "glm-5.1",
    maxOutputTokens: 131_072,
    sourceUrl: "https://docs.bigmodel.cn/cn/guide/start/model-overview",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["glm-5-turbo"],
    contextWindowTokens: 200_000,
    description: "面向 Agentic Engineering 的智谱旗舰模型，擅长复杂系统工程、编码和长程代理任务。",
    displayName: "GLM-5",
    family: "GLM-5",
    id: "glm-5",
    maxOutputTokens: 131_072,
    sourceUrl: "https://docs.bigmodel.cn/cn/guide/start/model-overview",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["glm-4-7", "glm-4.7-flash", "glm-4.7-flashx", "zai-glm-4.7"],
    contextWindowTokens: 200_000,
    description: "智谱 Agentic Coding 旗舰模型，强化编码、长任务规划、工具协作和复杂指令遵循。",
    displayName: "GLM-4.7",
    family: "GLM-4",
    id: "glm-4.7",
    maxOutputTokens: 131_072,
    sourceUrl: "https://docs.bigmodel.cn/cn/guide/start/model-overview",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 200_000,
    description: "智谱通用旗舰模型，重点提升高级编码、长文本处理、推理和 Agent 能力。",
    displayName: "GLM-4.6",
    family: "GLM-4",
    id: "glm-4.6",
    maxOutputTokens: 131_072,
    sourceUrl: "https://docs.bigmodel.cn/cn/guide/start/model-overview",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["glm-4.5-air", "glm-4.5-airx", "glm-4.5-x"],
    contextWindowTokens: 131_072,
    description: "智谱面向 Agent 的混合推理模型，支持思考与非思考模式，兼顾推理、编码和工具调用。",
    displayName: "GLM-4.5",
    family: "GLM-4",
    id: "glm-4.5",
    maxOutputTokens: 98_304,
    sourceUrl: "https://docs.bigmodel.cn/cn/guide/start/model-overview",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["glm-4-flash"],
    contextWindowTokens: 131_072,
    description: "智谱长文本通用模型，适合复杂任务和中文内容处理。",
    displayName: "GLM-4 Plus",
    family: "GLM-4",
    id: "glm-4-plus",
    maxOutputTokens: 4096,
    sourceUrl: "https://docs.bigmodel.cn/cn/guide/models/text/glm-4",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 1_000_000,
    description: "Anthropic 面向高难度代理、编码和专业任务的高级推理模型。",
    displayName: "Claude Opus 4.6",
    family: "Claude 4.6",
    id: "claude-opus-4-6",
    knowledgeCutoff: "2025-05",
    maxOutputTokens: 128_000,
    sourceUrl: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
    verifiedAt: VERIFIED_AT,
  },
  {
    contextWindowTokens: 1_000_000,
    description: "Anthropic 面向编码、代理与复杂推理的长上下文模型。",
    displayName: "Claude Sonnet 4.6",
    family: "Claude 4.6",
    id: "claude-sonnet-4-6",
    knowledgeCutoff: "2025-08",
    maxOutputTokens: 64_000,
    sourceUrl: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["claude-opus-4-5", "claude-haiku-4-5"],
    contextWindowTokens: 200_000,
    description: "Anthropic 通用长上下文模型，支持编码、视觉与扩展思考。",
    displayName: "Claude 4.5",
    family: "Claude 4.5",
    id: "claude-sonnet-4-5",
    maxOutputTokens: 64_000,
    sourceUrl: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
    verifiedAt: VERIFIED_AT,
  },
  {
    aliases: ["grok-4.20", "grok-4.20-0309-non-reasoning"],
    contextWindowTokens: 1_000_000,
    description: "xAI 长上下文通用模型，支持工具调用、视觉和结构化输出。",
    displayName: "Grok 4",
    family: "Grok",
    id: "grok-4.3",
    sourceUrl: "https://docs.x.ai/docs/models",
    verifiedAt: VERIFIED_AT,
  },
];

const normalizeModelId = (modelId: string) => {
  const id = modelId.trim().toLowerCase();
  const pathParts = id.split("/").filter(Boolean);
  return pathParts[pathParts.length - 1] || id;
};

export const getModelMetadata = (modelId?: string): ModelMetadata | undefined => {
  if (!modelId) return undefined;
  const normalized = normalizeModelId(modelId);

  for (const model of MODEL_METADATA) {
    const candidates = [model.id, ...(model.aliases || [])].map((id) => id.toLowerCase());
    if (
      candidates.some(
        (candidate) =>
          normalized === candidate ||
          normalized.startsWith(`${candidate}-20`) ||
          normalized.startsWith(`${candidate}-preview-`) ||
          normalized === `${candidate}-latest` ||
          normalized.startsWith(`${candidate}:`),
      )
    ) {
      return model;
    }
  }

  return undefined;
};

export const formatTokenCount = (tokens: number) => {
  if (tokens >= 1_000_000) {
    const value = tokens / 1_000_000;
    return `${Number.isInteger(value) ? value.toFixed(0) : value.toFixed(2).replace(/0+$/, "")}M`;
  }
  if (tokens >= 1000) {
    const value = tokens / 1000;
    return `${Number.isInteger(value) ? value.toFixed(0) : value.toFixed(1).replace(/\.0$/, "")}K`;
  }
  return String(tokens);
};
